services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: news_db
    ports:
    - 3306:3306

  mq:
    image: redis
    container_name: mq
    ports:
      - 6379:6379